import type { NextPage } from 'next'
import Head from 'next/head'
import { useRef } from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const store = useRef<{ record: Record<string, unknown> }>()
  const saveStore = (key: string, value: unknown) => {
    store.current ??= { record: {} }
    store.current.record[key] = value
    console.log(store.current.record)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js swc minify bug demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.wrapper}>
          <div>store JSON: { JSON.stringify(store.current) }</div>
          <button onClick={() => saveStore('foo', 1)}>add `foo: 1`</button>
          <button onClick={() => saveStore('bar', 2)}>add `bar: 2`</button>
        </div>
      </main>
    </div>
  )
}

export default Home
